### ISSUE TITLE
Wrong mods display and missing mods

### ISSUE THREAD

**Issue by ZaneDX** [Gloorf/POECraftingShenanigans#1]
Hi, I was trying to use your "Optimise with Fossils" option and also later checked "Display Mods" and I couldn't find some mods.

I used Shaper Profane Wand with ilvl 85 and later ilvl 100
I was trying to find the best option to roll Physical as Extra Lightning (ilvl 80 for highest tier) along with Elemental as Extra Chaos (ilvl 85 for highest tier), but I couldnt find it. So I tripple checked the list and it's not there.
I found PhysicalAddedAsFireUber3 and PhysicalAddedAsColdUber3 ID that represents Physical as Extra Fire/Cold Damage (I've checked it with recommended fossils to be sure) but that mods cannot appear on Shaper Wands.

**Comment by Gloorf** [comment]
This should be fixed in the latest release (https://github.com/Gloorf/POECraftingShenanigans/releases/tag/0.0.2). There was a (human) mistake on the shaper tag of wands, so the program was using the shaper tag of axes instead (hence why you had the physical as fire/cold which are axes mods)

Thanks for the report !
